config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "users#home"
  resources :users, only: [:index] do
    get 'cv', on: :collection
    get 'contact', on: :collection
  end
  resources :realisations, only: %i[new create edit update destroy] do
    get 'etudes', on: :collection
    get 'experiences_pro', on: :collection
  end
  resources :formations, only: %i[new create edit update destroy]
  resources :competences, only: %i[new create edit update destroy]
  resources :bureautiques, only: %i[new create edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bureautique.rb
class Bureautique < ApplicationRecord
  belongs_to :user
end

app/models/competence.rb
class Competence < ApplicationRecord
  belongs_to :user
end

app/models/formation.rb
class Formation < ApplicationRecord
  belongs_to :user
end

app/models/realisation.rb
class Realisation < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :realisations
  has_many :bureautiques
  has_many :formations
  has_many :competences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bureautiques_controller.rb
class BureautiquesController < ApplicationController
  before_action :set_bureautique, only: %i[edit update destroy]

  def new
    @bureautique = Bureautique.new
  end

  def create
    @bureautique = Bureautique.new(bureautique_params)
    @bureautique.user = current_user
    if @bureautique.save
      redirect_to users_path, notice: "Bureautique crée ! ☺"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bureautique.update(bureautique_params)
    redirect_to users_path, notice: "Bureautique mis à jour ! 😉"
  end

  def destroy
    @bureautique.destroy
    redirect_to users_path, notice: "Bureautique supprimé ! 😢"
  end


  private


  def set_bureautique
    @bureautique = Bureautique.find(params[:id])
  end

  def bureautique_params
    params.require(:bureautique).permit(:outil, :progression)
  end
end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController
  before_action :set_competence, only: %i[edit update destroy]

  def new
    @competence = Competence.new
  end

  def create
    @competence = Competence.new(competence_params)
    @competence.user = current_user
    if @competence.save
      redirect_to users_path, notice: "Competence crée ! ☺"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @competence.update(competence_params)
    redirect_to users_path, notice: "Competence mis à jour ! 😉"
  end

  def destroy
    @competence.destroy
    redirect_to users_path, notice: "Competence supprimé ! 😢"
  end


  private


  def set_competence
    @competence = Competence.find(params[:id])
  end

  def competence_params
    params.require(:competence).permit(:competence, :progression)
  end
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :set_formation, only: %i[edit update destroy]

  def new
    @formation = Formation.new
  end

  def create
    @formation = Formation.new(formation_params)
    @formation.user = current_user
    if @formation.save
      redirect_to users_path, notice: "Formation crée ! ☺"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @formation.update(formation_params)
    redirect_to users_path, notice: "Formation mis à jour ! 😉"
  end

  def destroy
    @formation.destroy
    redirect_to users_path, notice: "Formation supprimé ! 😢"
  end


  private


  def set_formation
    @formation = Formation.find(params[:id])
  end

  def formation_params
    params.require(:formation).permit(:annee_debut, :annee_fin, :emploi, :organisation, :ville, :detail, :experience)
  end
end

app/controllers/realisations_controller.rb
class RealisationsController < ApplicationController
  before_action :set_realisation, only: %i[edit update destroy]

  def new
    @realisation = Realisation.new
  end

  def create
    @realisation = Realisation.new(realisation_params)
    @realisation.user = current_user
    if @realisation.save
      redirect_to users_path, notice: "Réalisation crée ! ☺"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @realisation.update(realisation_params)
    redirect_to users_path, notice: "Réalisation mis à jour ! 😉"
  end

  def destroy
    @realisation.destroy
    redirect_to users_path, notice: "Réalisation supprimé ! 😢"
  end

  def etudes
    @realisations_etude = Realisation.where(categorie: 'etude')
  end

  def experiences_pro
    @realisations_pro = Realisation.where(categorie: 'experience pro')
  end


  private


  def set_realisation
    @realisation = Realisation.find(params[:id])
  end

  def realisation_params
    params.require(:realisation).permit(:titre, :description, :date, :categorie, photos: [])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    flash[:notice] = "Profil mis à jour ! 😉"
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[prenom nom introduction ambition emploi_voulu email telephone adresse])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:edit, :update]
  before_action :authenticate_user!, only: [:index]

  def index
    @realisations = Realisation.all
    @competences = Competence.all
    @bureautiques = Bureautique.all
    @formations_sans_type = Formation.where(experience: '')
    @formations = Formation.where(experience: 'formation')
    @stages = Formation.where(experience: 'stage')
    @experiences_pro = Formation.where(experience: 'experience pro')
  end

  def home
    @anais = User.first
  end

  def cv
    @competences = Competence.all
    @bureautiques = Bureautique.all
    @formations = Formation.where(experience: 'formation').order(annee_fin: :desc)
    @stages = Formation.where(experience: 'stage').order(annee_fin: :desc)
    @experiences_pro = Formation.where(experience: 'experience pro').order(annee_fin: :desc)
  end

  # def loisirs
  # end

  def contact
    @anais = User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bureautiques_helper.rb
module BureautiquesHelper
end

app/helpers/competences_helper.rb
module CompetencesHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/realisations_helper.rb
module RealisationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bureautiques/_form.html.erb
<div class="container">
  <%= simple_form_for @bureautique do |f| %>
    <%= f.input :outil %>
    <%= f.input :progression %>

    <div>
      <%= f.submit "OKay", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/bureautiques/edit.html.erb
<%= render 'form', bureautique: @bureautique %>

app/views/bureautiques/new.html.erb
<%= render 'form', bureautique: @bureautique %>

app/views/competences/_form.html.erb
<div class="container">
  <%= simple_form_for @competence do |f| %>
    <%= f.input :competence %>
    <%= f.input :progression %>

    <div>
      <%= f.submit "OKay", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/competences/edit.html.erb
<%= render 'form', competence: @competence %>

app/views/competences/new.html.erb
<%= render 'form', competence: @competence %>

app/views/formations/_form.html.erb
<div class="container">
  <%= simple_form_for @formation do |f| %>
    <%= f.input :annee_debut, as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :annee_fin, as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :emploi %>
    <%= f.input :organisation %>
    <%= f.input :ville %>
    <%= f.input :detail %>
    <%= f.input :experience, collection: ['experience pro', 'stage', 'formation'], prompt: "Choisis le type d'experience" %>
    <div>
      <%= f.submit "OKay", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/formations/edit.html.erb
<%= render 'form', formation: @formation %>

app/views/formations/new.html.erb
<%= render 'form', formation: @formation %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioAnais</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= render "shared/navbar" %>
    <div class="text-center">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/realisations/_form.html.erb
<div class="container">
  <%= simple_form_for @realisation do |f| %>
    <%= f.input :categorie, collection: ['experience pro', 'etude'], prompt: "Choisis le type d'experience" %>
    <%= f.input :titre %>
    <%= f.input :description %>
    <%= f.input :date, as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div>
      <%= f.submit "OKay", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/realisations/edit.html.erb
<%= render 'form', realisation: @realisation %>

app/views/realisations/etudes.html.erb
<div class="my-3">
  <h1>Mes études</h1>
  <% @realisations_etude.each do |real_etud| %>
    <h2 class="mt-4"><%= real_etud.titre %></h2>
    <p><%= real_etud.description %></p>
    <% if real_etud.photos.present? %>
      <div id="carousel<%=real_etud.id%>" class="carousel carousel-dark slide" data-bs-ride="carousel">
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%=real_etud.id%>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel<%=real_etud.id%>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        <div class="carousel-indicators">
          <% real_etud.photos.each_with_index do |photo, index| %>
            <button type="button" data-bs-target="#carousel<%=real_etud.id%>" data-bs-slide-to='<%= index %>' class="<%= 'active' if index.zero? %>" aria-current="<%= 'true' if index.zero? %>" aria-label='Photo n°<%=index + 1%>'></button>
          <% end %>
        </div>
        <div class="carousel-inner">
          <% real_etud.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
              <%= cl_image_tag photo.key, alt: "Photo n° #{index + 1}", class: "d-block w-100 rounded-5" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/realisations/experiences_pro.html.erb
<div class="my-3">
  <h1>Mes experiences professionelles</h1>
  <% @realisations_pro.each do |real_pro| %>
    <h2 class="mt-4"><%= real_pro.titre %></h2>
    <p><%= real_pro.description %></p>
    <% if real_pro.photos.attached? %>
      <% real_pro.photos.each_with_index do |photo, index| %>
        <div class="mt-3" data-aos="fade" data-aos-duration="1200" data-aos-easing="ease-in-sine" data-aos-offset="250">
          <%= cl_image_tag photo.key, alt: "Photo n° #{index + 1}", class: "d-block w-100 rounded-5 shadow" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/realisations/new.html.erb
<%= render 'form', realisation: @realisation %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="background" data-controller="navbar-button" data-navbar-button-target="button" data-action="click->navbar-button#animate" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
  <button class="menu__icon" data-navbar-button-target="menuIcon">
    <span></span>
    <span></span>
    <span></span>
  </button>
</div>
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-body text-end d-flex flex-column gap-5 mt-5">
    <div class="border-bottom d-flex flex-column gap-3 border-3 mt-4">
      <% if !user_signed_in? %>
        <%= link_to "connexion", new_user_session_path %>
      <% else %>
        <%= link_to "Tes infos !", edit_user_registration_path(current_user) %>
        <%= link_to "Ajouter/modifier/supprimer", users_path %>
        <%= link_to "Deconnexion", destroy_user_session_path, data: {turbo_method: :delete}%>
        <br>
      <% end %>
    </div>
    <%= link_to "Mon CV", cv_users_path %>
    <%= link_to "Mes études", etudes_realisations_path %>
    <%= link_to "Mes expériences professionnels", experiences_pro_realisations_path %>
    <%#= link_to "Loisirs", loisirs_users_path %>
    <%= link_to "Mes contact", contact_users_path %>
    <%= link_to "Mon profil", root_path %>
  </div>
</div>

app/views/users/contact.html.erb
<div class="my-3">
  <h1>Contact</h1>

<%# Methode 1 : Card avec infos cachées %>
  <div class="card">
    <p>
      <span><%= image_tag "icons/phone-call.png" %> Téléphone</span>
      <span class="hidden-info"><%= link_to @anais.telephone, "tel:#{@anais.telephone}"%></span>
    </p>
    <p>
      <span><%= image_tag "icons/email.png" %> Email</span>
      <span class="hidden-info"><%= link_to @anais.email, "mailto:#{@anais.email}"%></span>
    </p>
    <p>
      <span><%= image_tag "icons/location.png" %> Adresse</span>
      <span class="hidden-info"><%= link_to @anais.adresse, "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(@anais.adresse)}", target: "_blank"%></span>
    </p>
    <p>
      <span><%= image_tag "icons/info.png" %> Infos</span>
      <span class="hidden-info">Permis B <br> Brevet de secourisme</span>
    </p>
  </div>


<%# Methode 2 : Comme sur le CV %>
  <div class="d-flex ms-5 align-items-baseline fs-4 gap-3 mt-5">
    <div class="background-green px-3 py-1">
      <i class="fa-solid fa-phone-volume icone-white"></i>
    </div>
    <%= link_to @anais.telephone, "tel:#{@anais.telephone}" %>
  </div>

  <div class="d-flex ms-5 align-items-baseline fs-4 gap-3 mt-5">
    <div class="background-green px-3 py-1">
      <i class="fa-solid fa-at icone-white"></i>
    </div>
    <%= link_to @anais.email, "mailto:#{@anais.email}" %>
  </div>

  <% if @anais.adresse.present? %>
    <div class="d-flex ms-5 align-items-center fs-4 gap-3 mt-5 text-start">
      <div class="background-green px-3 py-1">
        <i class="fa-solid fa-location-dot icone-white"></i>
      </div>
      <%= link_to @anais.adresse, "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(@anais.adresse)}", target: "_blank" %>
    </div>
  <% end %>

  <div class="d-flex ms-5 align-items-baseline fs-4 gap-3 mt-5">
    <div class="background-green px-3 py-1">
      <i class="fa-solid fa-car-rear icone-white"></i>
    </div>
    <p>Permis B</p>
  </div>

<%# Methode 3 : Style carte de visite %>
  <div class="rounded-4 py-3 mt-5 special-card">
    <%= link_to "tel:#{@anais.telephone}" do %>
      <div class="special-field d-flex align-items-baseline mx-3 ps-2 fs-4 gap-3">
        <div class="ps-3 py-1">
          <i class="fa-solid fa-phone-volume"></i>
        </div>
        <p><%= @anais.telephone %></p>
      </div>
    <% end %>

    <%= link_to "mailto:#{@anais.email}" do %>
      <div class="special-field d-flex align-items-baseline mx-3 ps-2 fs-4 gap-3 mt-5">
        <div class="ps-3 py-1">
          <i class="fa-solid fa-at"></i>
        </div>
        <p><%= @anais.email %></p>
      </div>
    <% end %>


    <% if @anais.adresse.present? %>
      <%= link_to "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(@anais.adresse)}", target: "_blank" do %>
        <div class="special-field d-flex align-items-center mx-3 ps-2 fs-4 gap-3 mt-5 text-start">
          <div class="ps-3 py-1">
            <i class="fa-solid fa-location-dot"></i>
          </div>
          <p><%= @anais.adresse %></p>
        </div>
      <% end %>
    <% end %>

    <div class="special-field d-flex align-items-baseline mx-3 ps-2 fs-4 gap-3 mt-5">
      <div class="ps-3 py-1">
        <i class="fa-solid fa-car-rear"></i>
      </div>
      <p class="mb-0">Permis B</p>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<%= render 'form', anais: @anais %>

app/views/users/home.html.erb
<div class="d-md-flex flex-wrap my-3">
  <div class="d-md-flex mx-auto">
    <div class="h-25">
      <h1><%= @anais.prenom %> <%= @anais.nom %></h1>
      <h2><%= @anais.emploi_voulu %></h2>
    </div>
    <div class="image-container mt-5">
      <%= image_tag "avatar.jpg" %>
    </div>
  </div>
  <div class="text-start d-md-flex flex-column width-50 mt-5">
    <h1>Qui suis-je ?</h1>
    <p><%= @anais.introduction %></p>
  </div>
  <div class="text-end mt-5">
    <h1>Mes ambitions</h1>
    <p><%= @anais.ambition %></p>
  </div>
</div>

app/views/users/index.html.erb
<h1>toutes les modifs ici 🎨</h1>

<h2 class="my-3">Réalisations</h2>
<%= link_to "Ajouter 🖌", new_realisation_path %><br>
<ul>
  <% @realisations.each do |realisation| %>
    <li class="mb-3 text-info">
      (<%= realisation.categorie %>)
      <%= realisation.titre %> <%= realisation.date.strftime("%Y") if realisation.date.present? %>
      <%= realisation.description %>
      <div class="d-flex justify-content-evenly">
        <%= link_to "Modifier 🎨", edit_realisation_path(realisation) %>
        <%= link_to 'Détruire 💣', realisation_path(realisation), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{realisation.titre}, vraiment ? SUR ?" } %>
      </div>
    </li>
  <% end %>
</ul>

<h2 class="mt-5">Formations</h2>
<%= link_to "Ajouter 🖌", new_formation_path %><br>
<ul>
  <h5>Formations : </h5>
  <% @formations.each do |formation| %>
    <li class="mb-3 text-info">
      <%= formation.annee_debut.strftime("%Y")  %> - <%= formation.annee_fin.strftime("%Y")  %>
      <%= formation.emploi %> chez <%= formation.organisation %> à <%= formation.ville %>
      <div class="d-flex justify-content-evenly">
        <%= link_to "Modifier 🎨", edit_formation_path(formation) %>
        <%= link_to 'Détruire 💣', formation_path(formation), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{formation.emploi} (#{formation.organisation}), vraiment ? SUR ?" } %>
      </div>
    </li>
  <% end %>
  <h5 class="mt-5">Stages :</h5>
  <% @stages.each do |stage| %>
    <li class="mb-3 text-info">
      <%= stage.annee_debut.strftime("%Y")  %> - <%= stage.annee_fin.strftime("%Y")  %>
      <%= stage.emploi %> chez <%= stage.organisation %> à <%= stage.ville %>
      <div class="d-flex justify-content-evenly">
        <%= link_to "Modifier 🎨", edit_formation_path(stage) %>
        <%= link_to 'Détruire 💣', formation_path(stage), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{stage.emploi} (#{stage.organisation}), vraiment ? SUR ?" } %>
      </div>
    </li>
  <% end %>
  <h5 class="mt-5">Experiences pro :</h5>
    <% @experiences_pro.each do |experience_pro| %>
    <li class="mb-3 text-info">
      <%= experience_pro.annee_debut.strftime("%Y")  %> - <%= experience_pro.annee_fin.strftime("%Y")  %>
      <%= experience_pro.emploi %> chez <%= experience_pro.organisation %> à <%= experience_pro.ville %>
      <%= experience_pro.detail %>
      <div class="d-flex justify-content-evenly">
        <%= link_to "Modifier 🎨", edit_formation_path(experience_pro) %>
        <%= link_to 'Détruire 💣', formation_path(experience_pro), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{experience_pro.emploi} (#{experience_pro.organisation}), vraiment ? SUR ?" } %>
      </div>
    </li>
  <% end %>
  <h5 class="mt-5">Les oublies (sans type défini) :</h5>
      <% @formations_sans_type.each do |oublie| %>
    <li class="mb-3 text-info">
      <%= oublie.annee_debut.strftime("%Y")  %> - <%= oublie.annee_fin.strftime("%Y")  %>
      <%= oublie.emploi %> chez <%= oublie.organisation %> à <%= oublie.ville %>
      <div class="d-flex justify-content-evenly">
        <%= link_to "Modifier 🎨", edit_formation_path(oublie) %>
        <%= link_to 'Détruire 💣', formation_path(oublie), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{oublie.emploi} (#{oublie.organisation}), vraiment ? SUR ?" } %>
      </div>
    </li>
  <% end %>
</ul>

<h2 class="mt-5">Compétence</h2>
<%= link_to "Ajouter 🖌", new_competence_path %><br>
<ul>
  <% @competences.each do |competence| %>
    <li class="mt-2 text-info">
      <%= competence.competence %> : <%= competence.progression %>%
      <div class="d-flex justify-content-evenly">
        <%= link_to "Modifier 🎨", edit_competence_path(competence) %>
        <%= link_to 'Détruire 💣', competence_path(competence), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{competence.competence}, vraiment ? SUR ?" } %>
      </div>
    </li>
  <% end %>
</ul>

<h2 class="mt-5">Outils bureautique</h2>
<%= link_to "Ajouter 🖌", new_bureautique_path %><br>
<ul>
  <% @bureautiques.each do |bureautique| %>
    <li class="mt-2 text-info">
      <%= bureautique.outil %> : <%= bureautique.progression %>%
      <%= link_to "Modifier 🎨", edit_bureautique_path(bureautique) %>
      <%= link_to 'Détruire 💣', bureautique_path(bureautique), data: { turbo_method: :delete, turbo_confirm: "Supprimer #{bureautique.outil}, vraiment ? SUR ?" } %>
    </li>
  <% end %>
</ul>